# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blink < Formula
  desc "Open Source stream processing framework"
  homepage "https://github.com/usedatabrew/blink"
  version "1.6.1"

  on_macos do
    url "https://github.com/usedatabrew/blink/releases/download/v1.6.1/blink_1.6.1_darwin_amd64.tar.gz"
    sha256 "614363ea36e92113f8bbbdc0698648bbd42990cafb69567d2bafbc29b7e7baac"

    def install
      bin.install "blink"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Blink
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/usedatabrew/blink/releases/download/v1.6.1/blink_1.6.1_linux_amd64.tar.gz"
      sha256 "68abc4da99db6abb6cb917a9f08d4f29140f9ede60cece5b4894fc51c7d28438"

      def install
        bin.install "blink"
      end
    end
  end
end
