# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blink < Formula
  desc "Open Source stream processing framework"
  homepage "https://github.com/usedatabrew/blink"
  version "1.11.2"

  on_macos do
    url "https://github.com/usedatabrew/blink/releases/download/v1.11.2/blink_1.11.2_darwin_amd64.tar.gz"
    sha256 "372126bdf317b8a70e658d20f56b3801b3e5748602ce05201ab223d2b7238c83"

    def install
      bin.install "blink"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Blink
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/usedatabrew/blink/releases/download/v1.11.2/blink_1.11.2_linux_amd64.tar.gz"
      sha256 "50e4505d0543fd01a673a3e09d8623b09b3db7f72ef587d8e3132749dd0b4ba3"

      def install
        bin.install "blink"
      end
    end
  end
end
