# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blink < Formula
  desc "Open Source stream processing framework"
  homepage "https://github.com/usedatabrew/blink"
  version "1.10.2"

  on_macos do
    url "https://github.com/usedatabrew/blink/releases/download/v1.10.2/blink_1.10.2_darwin_amd64.tar.gz"
    sha256 "ee02a0167e18ecdad572f7a0c9b0dbb47cd9dbe9876af3dd509b5b212db500bc"

    def install
      bin.install "blink"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Blink
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/usedatabrew/blink/releases/download/v1.10.2/blink_1.10.2_linux_amd64.tar.gz"
      sha256 "f5ed2ff25dc38164683e5e4e5653e275399169112866ecd977585b7c31f4051a"

      def install
        bin.install "blink"
      end
    end
  end
end
