# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datablink < Formula
  desc "Open Source stream processing framework"
  homepage "https://github.com/usedatabrew/blink"
  version "1.16.3"

  on_macos do
    url "https://github.com/usedatabrew/blink/releases/download/v1.16.3/blink_1.16.3_darwin_amd64.tar.gz"
    sha256 "0bb73479e91ecc48022ae4536683ad7248f799eb2f9e3b9b4789094fe5ffcad9"

    def install
      bin.install "datablink"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Datablink
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/usedatabrew/blink/releases/download/v1.16.3/blink_1.16.3_linux_amd64.tar.gz"
      sha256 "77e8d0f4f2046669ee5d3a83d4b9661a7d33c3edc868601014308a875d817d6a"

      def install
        bin.install "datablink"
      end
    end
  end
end
