# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datablink < Formula
  desc "Open Source stream processing framework"
  homepage "https://github.com/usedatabrew/blink"
  version "1.16.4"

  on_macos do
    url "https://github.com/usedatabrew/blink/releases/download/v1.16.4/blink_1.16.4_darwin_amd64.tar.gz"
    sha256 "8933e0e9047672a3422f9cd4e5ffa34b98fb51937f42121280e2a5017d28e97a"

    def install
      bin.install "datablink"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Datablink
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/usedatabrew/blink/releases/download/v1.16.4/blink_1.16.4_linux_amd64.tar.gz"
      sha256 "80151608c1e0741dd3a26507acba8d5435e8c5b85591f6cf06e163c3cd2a4e41"

      def install
        bin.install "datablink"
      end
    end
  end
end
