service:
  enable_influx: true
  group_name: org_id_12
  pipeline_id: 120
  influx:
    host: https://eu-central-1-1.aws.cloud2.influxdata.com
    token: dwWFG-NXl8uy0dmiptLjN1-B1-5JIlyEnwCHVxmPgY-6o6f62-G09dtYDg1SEYk6mL3wGG_7DIMVer8Yoe-e9Q==
    org: DataBrew, Inc.
    bucket: databrew_ingestor
    group_name: org_11
    pipeline_id: 123
  reload_on_restart: false
  stream_schema:
    - stream: public.flights
      columns:
        - name: flight_id
          databrewType: Int32
          nativeConnectorType: integer
          pk: true
          nullable: false
        - name: flight_number
          databrewType: Int32
          nativeConnectorType: integer
          pk: false
          nullable: true
        - name: departure_airport
          databrewType: String
          nativeConnectorType: character varying
          pk: false
          nullable: true
        - name: arrival_airport
          databrewType: String
          nativeConnectorType: character varying
          pk: false
          nullable: true
        - name: departure_date
          databrewType: Date32
          nativeConnectorType: date
          pk: false
          nullable: true
        - name: arrival_date
          databrewType: Date32
          nativeConnectorType: date
          pk: false
          nullable: true
        - name: departure_time
          databrewType: String
          nativeConnectorType: character varying
          pk: false
          nullable: true
        - name: arrival_time
          databrewType: String
          nativeConnectorType: character varying
          pk: false
          nullable: true
        - name: flight_duration
          databrewType: Float64
          nativeConnectorType: double precision
          pk: false
          nullable: true
        - name: flight_status
          databrewType: String
          nativeConnectorType: character varying
          pk: false
          nullable: true
        - name: id
          databrewType: Int32
          nativeConnectorType: integer
          pk: true
          nullable: false

source:
  driver: postgres_cdc
  config:
    host: databrew-testing-instance.postgres.database.azure.com
    slot_name: databrew_replication_slot_15_1123
    user: postgres
    password: Lorem123
    port: 5432
    schema: public
    stream_snapshot: true
    snapshot_memory_safety_factor: 0.1
    snapshot_batch_size: 10000
    database: mocks
    tables:
      - flights

sink:
  driver: stdout
  config: { }