service:
  id: 123
  pipeline_id: 1234
  enable_etcd_registry: true
  etcd:
    host: http://137.135.132.105:2379
  reload_on_restart: false
  stream_schema:
    - stream: flights
      columns:
        - name: flight_id
          databrewType: Int32
          nativeConnectorType: integer
          pk: false
          nullable: false
        - name: flight_number
          databrewType: Int32
          nativeConnectorType: integer
          pk: false
          nullable: true
        - name: departure_airport
          databrewType: String
          nativeConnectorType: character varying
          pk: false
          nullable: true
        - name: arrival_airport
          databrewType: String
          nativeConnectorType: character varying
          pk: false
          nullable: true
        - name: departure_date
          databrewType: Date32
          nativeConnectorType: date
          pk: false
          nullable: true
        - name: arrival_date
          databrewType: Date32
          nativeConnectorType: date
          pk: false
          nullable: true
        - name: departure_time
          databrewType: String
          nativeConnectorType: character varying
          pk: false
          nullable: true
        - name: arrival_time
          databrewType: String
          nativeConnectorType: character varying
          pk: false
          nullable: true
        - name: flight_duration
          databrewType: Float64
          nativeConnectorType: double precision
          pk: false
          nullable: true
        - name: flight_status
          databrewType: String
          nativeConnectorType: character varying
          pk: false
          nullable: true
        - name: id
          databrewType: Int32
          nativeConnectorType: integer
          pk: true
          nullable: false

source:
  driver: postgres_cdc
  config:
    host: databrew-testing-instance.postgres.database.azure.com
    slot_name: databrew_replication_slot_15_11910
    user: postgres
    password: Lorem123
    port: 5432
    schema: public
    stream_snapshot: true
    snapshot_memory_safety_factor: 0.1
    snapshot_batch_size: 5000
    database: mocks
    tables:
      - flights

processors:
  - driver: openai
    config:
      api_key: ""
      model: ""
      source_field: "example"
      target_field: "open_ai_result"
      prompt: "Test OpenAI Prompt"
      stream_name: "flights"

sink:
  driver: postgres
  config:
    host: databrew-testing-instance.postgres.database.azure.com
    user: postgres
    password: Lorem123
    port: 5432
    schema: public
    database: mocks_manual_target