name: Create release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: Install go-Kafka dep
        run: go get gopkg.in/confluentinc/confluent-kafka-go.v1/kafka

      - name: Run mod tidy
        run: go mod tidy
        
      - name: Build binary
        run: cd cmd/blink && go build -tags dynamic blink/cmd/blink