name: Create git tag from commits
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  svu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: "Generate semantic version"
        id: generate_next_version
        uses: obfu5c8/action-svu@v1.0.0
        with:
          force-increment: true
      - run: |
          git tag ${{ steps.generate_next_version.outputs.version }}
          git push --tags